Game
WildCodeSchool/reims-0519-java-sales-war pull request #6
Opened 2019-07-10 16:15 UTC by cakocako

2019-07-10 17:23 UTC, rocambille requested changes

2019-07-10 17:23 UTC, wasthishelpful commented on src/main/java/com/saleswar/game/repository/PlayerRepository.java
> +    private List<Player> rooms;
C’est une liste de player ou des rooms ?

2019-07-10 17:23 UTC, wasthishelpful commented on src/main/java/com/saleswar/game/controllers/GameController.java
> +    @PostMapping("/scores")
Ça retourne un template de vue : c’est un get

2019-07-11 07:24 UTC, cakocako commented on src/main/java/com/saleswar/game/repository/PlayerRepository.java
> +    private List<Player> rooms;
changes made

2019-07-11 21:39 UTC, closed without merging